= TTCN-3 Limitations in this Version
:toc:

The present Test Executor is an implementation of TTCN–3 Core Language standard (<<14-references.adoc#_1, [1]>>) with support of ASN.1 (<<14-references.adoc#_3, [3]>>). However, the TTCN–3 language constructs detailed in <<14-references.adoc#_27, [27]>> are not supported in the current version of the Test Executor on both the C and the Java side.
The following list extend that list, with the TTCN–3 language constructs that are not supported, in addition, in the current version of the Java side of the Test Executor.

When applicable, the relevant clause of the standard text (<<14-references.adoc#_1, [1]>>) is given within parentheses after each limitation. The list of ASN.1 related limitations can be found in chapter *4.25*.

* The `update`, `interleave`, `label`, `goto` statements are not yet supported. (19.7, 19.8, 20.4 and 22.3.1 in <<14-references.adoc#_1, [1]>>)
* The `hostId` predefined function is not yet supported.

* Additionally the `@profiler.start`, `@profiler.stop`, `string2ttcn` TITAN extensions are also not yet supported on the Java side.
* The `@profiler.running` TITAN extension is also not supported.
* Concatenating template strings is not yet supported on the Java side.

WARNING: The current version of the Java side of the Test Executor is just a prototype version. Please note that there might still be some changes in some of its APIs.
