// This external class skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version 8.2.0
// for ebotbar (ebotbar@ebotbar-VirtualBox) on Wed Jun  8 16:31:03 2022

// Copyright (c) 2000-2021 Ericsson Telecom AB

// This file is not re-generated after a clean build, since the generated version does not compile
// (the external parameter needed to be added to the base constructor call manually)

#include "oop_ext.hh"

namespace oop__ext {

CHARSTRING ExternalSub::test__result()
{
// manually added code for testing:
return ret_val;
}

ExternalSub::ExternalSub(const INTEGER& par1, const CHARSTRING& par2, const INTEGER& c1, const FLOAT& c2, const OCTETSTRING& extpar)
: ExternalBase(par1, par2, extpar), c1(const_c1), c2(const_c2)
{
const_c1 = c1;
const_c2 = c2;

// manually added code for testing:
CHARSTRING separator("_");
ret_val = int2str(c1) + separator + float2str(c2) + separator + oct2str(extpar);
}

ExternalSub::~ExternalSub()
{
try {

} catch (...) {
fprintf(stderr, "Unhandled exception or dynamic test case error in the destructor of class `ExternalSub'. Terminating application.\n");
exit(EXIT_FAILURE);
}
}

void ExternalSub::log() const
{
TTCN_Logger::log_event_str("ExternalSub ( ");
ExternalBase::log();
TTCN_Logger::log_event_str(" )");
}


} /* end of namespace */

