// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R5A
// for ebotbar (ebotbar@ebotbarVB) on Thu Dec  6 16:47:16 2018

// Copyright (c) 2000-2020 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "PortA2.hh"
#include "B.hh"

namespace B {

PortA2_PROVIDER::PortA2_PROVIDER(const char *par_port_name)
	: PORT(par_port_name)
{

}

PortA2_PROVIDER::~PortA2_PROVIDER()
{

}

void PortA2_PROVIDER::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void PortA2_PROVIDER::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void PortA2_PROVIDER::Handle_Fd_Event_Error(int /*fd*/)
{

}

void PortA2_PROVIDER::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void PortA2_PROVIDER::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void PortA2_PROVIDER::Handle_Timeout(double time_since_last_call) {}*/

void PortA2_PROVIDER::user_map(const char * /*system_port*/)
{

}

void PortA2_PROVIDER::user_unmap(const char * /*system_port*/)
{

}

void PortA2_PROVIDER::user_start()
{

}

void PortA2_PROVIDER::user_stop()
{

}

void PortA2_PROVIDER::outgoing_send(const INTEGER& send_par)
{
	incoming_message(send_par * 10 + 3);
}

} /* end of namespace */

