// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R5A
// for ebotbar (ebotbar@ebotbarVB) on Thu Jan 10 16:00:13 2019

// Copyright (c) 2000-2021 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "PortB_RT.hh"

namespace B {

PortB__RT::PortB__RT(const char *par_port_name)
	: PortB__RT_BASE(par_port_name)
{

}

PortB__RT::~PortB__RT()
{

}

void PortB__RT::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void PortB__RT::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void PortB__RT::Handle_Fd_Event_Error(int /*fd*/)
{

}

void PortB__RT::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void PortB__RT::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void PortB__RT::Handle_Timeout(double time_since_last_call) {}*/

void PortB__RT::user_map(const char * /*system_port*/)
{

}

void PortB__RT::user_unmap(const char * /*system_port*/)
{

}

void PortB__RT::user_start()
{

}

void PortB__RT::user_stop()
{

}

void PortB__RT::outgoing_send(const OCTETSTRING& send_par, FLOAT* timestamp_redirect)
{
	if (timestamp_redirect != NULL) {
		*timestamp_redirect = TTCN_Runtime::now();
	}
	incoming_message(oct2str(send_par), TTCN_Runtime::now());
}

} /* end of namespace */

