// This external class skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version 7/CAX 105 7730 R2A
// for  (ethlel@HU-00001378) on Thu Dec  3 19:59:19 2020

// Copyright (c) 2000-2021 Ericsson Telecom AB

// You may modify this file. Complete the bodies of empty functions and
// add your member functions here.

#include <TTCN3.hh>

namespace Sem__5010103__externalClasses__001 {

#include "Int_List.hh"

void Int__List::add(const INTEGER& v)
{

}

INTEGER Int__List::get(const INTEGER& index)
{

}

Int__List::Int__List()
: OBJECT()
{

}

Int__List::~Int__List()
{
try {

} catch (...) {
fprintf(stderr, "Unhandled exception or dynamic test case error in destructor of class `Int__List'");
exit(EXIT_FAILURE);
}
}

void Int__List::log() const
{
TTCN_Logger::log_event_str("Int_List: { ");
TTCN_Logger::log_event_str(" }");
}


} /* end of namespace */

