// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R4C
// for ebotbar (ebotbar@ebotbarVB) on Wed Nov 28 12:07:59 2018

// Copyright (c) 2000-2020 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "PortTransBasic.hh"

namespace realtimeTimestampPortTranslation {

PortTransBasic::PortTransBasic(const char *par_port_name)
	: PortTransBasic_BASE(par_port_name)
{

}

PortTransBasic::~PortTransBasic()
{

}

void PortTransBasic::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void PortTransBasic::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void PortTransBasic::Handle_Fd_Event_Error(int /*fd*/)
{

}

void PortTransBasic::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void PortTransBasic::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void PortTransBasic::Handle_Timeout(double time_since_last_call) {}*/

void PortTransBasic::user_map(const char * /*system_port*/)
{

}

void PortTransBasic::user_unmap(const char * /*system_port*/)
{

}

void PortTransBasic::user_start()
{

}

void PortTransBasic::user_stop()
{

}

void PortTransBasic::outgoing_send(const OCTETSTRING& /*send_par*/)
{

}

} /* end of namespace */

